# Generated by Django 5.0.3 on 2024-04-04 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='unidade',
            field=models.CharField(blank=True, choices=[('crea', 'CREA'), ('cras_bairro_da_paz', 'CRAS - Bairro da Paz'), ('cras_bairro_panorama', 'CRAS - Bairro Panorama'), ('cras_serra_pelada', 'CRAS - Serra Pelada'), ('setor_idoso', 'Setor Idoso'), ('setor_adolescente', 'Setor Criança/Adolescente')], max_length=20),
        ),
    ]
