# Generated by Django 5.0.3 on 2024-04-04 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_alter_dadosresponsavel_datanascimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acolhimento',
            name='causaAcolhimento',
            field=models.TextField(blank=True, null=True, verbose_name='Causa do Acolhimento'),
        ),
        migrations.AlterField(
            model_name='acolhimento',
            name='dataEntrada',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Entrada'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='cpf',
            field=models.CharField(max_length=14, unique=True),
        ),
    ]
